runtime: nodejs18
env: standard

instance_class: F2

automatic_scaling:
  target_cpu_utilization: 0.9
  min_instances: 1
  max_instances: 40
  target_concurrent_requests: 100
  max_concurrent_requests: 10000

env_variables:
  NODE_ENV: production

handlers:
  - url: /.*
    script: auto
    secure: always
    http_headers:
      X-Content-Type-Options: nosniff
      X-Frame-Options: DENY
      X-XSS-Protection: 1; mode=block
      Cache-Control: public, max-age=300 